#!/usr/bin/env php
<?php

if (1 == $argc) {
    echo <<<DOC
Usage: sky command [param ...]
Commands are:
  s - run PHP web-server
  d - list dirs (from current dir)
  php - lint PHP files (from current dir)
  jet - lint Jet files
  m [id] - read tmemo cell from memory
  c - Reparse controllers list
  cache - Drop all cache
  a - show actions
  g - check globals

DOC;
    exit;
}

$d = 'd' == $argv[1];
if ($d || 'php' == $argv[1]) {
    require __DIR__ . '/w2/rare.php'; # add dir to the PATH where sky.bat placed
    $dirs = Rare::walk_dirs('.');
    if ($d) {
        print_r($dirs);
    } else foreach($dirs as $one) {
        $files = Rare::list_path($one, 'is_file');
        foreach($files as $one)
            system("php -l $one");
    }
} elseif ('s' == $argv[1]) {
    system("php -S localhost:" . ($argv[2] ?? 8888));
} else {
    define('DIR_R', getcwd());
    $dir_m = 'main';
    do {
        $dir = getcwd();
        if ($found = is_file("$dir_m/gate.php") && is_dir('var'))
            break;
        $dir_m = basename($dir);
        chdir('..');
    } while($dir != getcwd());

    if (!$found)
        exit("SKY application not found\n");
    define('DIR', $dir);
    define('DIR_M', $dir_m);
    require "$dir_m/conf.php";

    $sky  = new SKY;
    $sky->load();
    new Console($argv);
}

echo "\n";
